esp32:
  board: lolin_s2_mini

substitutions:
  hide_ams_sensors: 'true'
  led_pin: GPIO16
  spi2_type: SPI2 #SPI2,SPI3,any,hardware #TODO: should this be hardware? 
  spi2_clk_pin: GPIO36
  spi2_miso_pin: GPIO37
  spi2_mosi_pin: GPIO35
  rfid0_spi_interface: SPI2
  rfid0_ss_pin: GPIO34
  #rfid1_spi_interface: SPI2
  #rfid1_clk_pin: GPIO21
  ## rfid1_spi_interface: SPI2
  ## rfid1_clk_pin: GPIO08

# D1 Mini S2 Boards will reboot when doing tasks like writing to PN532 unless wifi power is reduced
wifi:
  output_power: 10 # https://github.com/esphome/issues/issues/3988#issuecomment-1449954758
  
packages: 
  openspool-mini: !include openspool-mini.yaml
  improv-serial: !include conf.d/improv-serial.yaml
  improv-bluetooth: !include conf.d/improv-bluetooth.yaml

# The s2 is pushing the limits of its cpu,
# Especially the fake clones without PSRAM
# Remove components to improve performance
sensor: 
  - id: !remove loop_time
  - id: !remove openspool_wifi_signal
  - id: !remove openspool_ssid
  - id: !remove openspool_ip_address
  - id: !remove free_psram